version: '3.9'
services:
  go:
    build:
      dockerfile: deploy/prod/go/Dockerfile
    env_file:
      - deploy/prod/.env
    depends_on:
      - postgres
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: always
  postgres:
    image: postgres:16.2-alpine3.19
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - deploy/prod/postgres/.env.prod
    ports:
      - ${FORWARD_DATABASE_PORT:-5432}:5432
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -p 5432' ]
      interval: 3s
      timeout: 3s
      retries: 10
    restart: always
volumes:
  postgres_data: