version: '3.9'
services:
  go:
    build:
      dockerfile: deploy/prod/go/Dockerfile
    env_file:
      - deploy/prod/.env
    depends_on:
      - mongo
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: always
  mongo:
    image: mongo:7.0.5
    volumes:
      - mongo_data:/data/db
    ports:
      - ${FORWARD_DATABASE_PORT:-27017}:27017
    env_file:
      - deploy/prod/mongo/.env.prod
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 3s
      timeout: 3s
      retries: 10
    restart: always
volumes:
  mongo_data: